name: Go

on:
  push:
    tags:
      - v*
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Install dependencies
      run: |
        go version
    # - name: Golangci-lint
    #   uses: golangci/golangci-lint-action@v2
    #   with:
    #     # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
    #     version: v1.43
    - name: Install golangci-lint
      run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.43

    - name: Run golangci-lint
      run: $(go env GOPATH)/bin/golangci-lint run --out-format checkstyle > checkstyle.xml 
    - name: Run vet
      run: |
        go vet .
    - name: Test
      run: go test -v -coverpkg=./... -coverprofile=profile.cov ./... -json > test_report.json
    - name: Coverage
      run: go tool cover -func profile.cov
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}